#!/usr/bin/env bash

set -euox pipefail

IMAGE="registry.gitlab.com/rainevi/fillaripolleri/client"
COMMIT="$(git rev-parse --verify HEAD)"

RELEASE=master
CHART_PATH=/Users/raine/code/kubernetes/my-kube/fillaripolleri

docker build -t $IMAGE .
docker tag $IMAGE $IMAGE:$COMMIT
docker tag $IMAGE $IMAGE:latest
docker push $IMAGE

helm upgrade \
  --reuse-values \
  --set client.tag="$COMMIT" \
  $RELEASE $CHART_PATH
