#!/usr/bin/env bash

set -euox pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root/client"

image="registry.fsn.raine.dev/fillaripolleri/client"
commit="$(git rev-parse --verify HEAD)"

docker build -t $image .
docker tag $image "$image:$commit"
docker tag $image "$image:latest"
docker push $image

image_with_sha="$(docker inspect --format='{{index .RepoDigests 0}}' $image:latest)"

helm upgrade \
	--reuse-values \
	--set client.image="$image_with_sha" \
	fillaripolleri "$repo_root/deploy/chart"
