{{- $fullName := include "fillaripolleri.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: fillaripolleri-service-tls
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-client
            port:
              number: {{ .Values.client.port }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-server
            port:
              number: {{ .Values.server.port }}
