INSERT INTO topic_category (id, name) VALUES
  (69, 'Triathlon/aika-ajo'),
  (54, 'Maantie'),
  (55, 'Cyclocross'),
  (56, 'Hybridit'),
  (57, 'Joustamattomat'),
  (70, 'Fatbiket'),
  (58, 'Etujousitetut'),
  (72, 'Täysjousitetut 80-125mm'),
  (74, 'Täysjousitetut 130-155mm'),
  (75, 'Täysjousitetut 160-210mm'),
  (63, 'Yksivaihteiset'),
  (61, 'Napavaihteiset'),
  (62, 'Ketjuvaihteiset'),
  (5, 'Lasten'),
  (52, 'Fiksit'),
  (60, 'Vintage/retro'),
  (51, 'BMX'),
  (79, 'Dirt/street'),
  (77, 'Cargo bikes'),
  (53, 'Muille osastoille sopimattomat'),
  (84, 'Sähköpyörät (maantie)'),
  (85, 'Sähköpyörät (maasto)'),
  (86, 'Sähköpyörät (muut)'),
  (8, 'Rungot'),
  (10, 'Keulat ja iskunvaimentimet'),
  (13, 'Kiekot'),
  (50, 'Renkaat'),
  (23, 'Satulat ja tolpat'),
  (27, 'Tangot ja stemmit'),
  (11, 'Voimansiirto'),
  (12, 'Jarrut'),
  (82, 'Sähköosat'),
  (14, 'Vaatteet'),
  (15, 'Kypärät ja suojat'),
  (16, 'Kengät'),
  (44, 'Elektroniikka'),
  (17, 'Muut');
