#!/usr/bin/env bash
set -xeuo pipefail

image="registry.raine.dev/fillaripolleri-server"
commit="$(git rev-parse --verify HEAD)"

docker build -t $image .
docker tag $image "$image:$commit"
docker tag $image "$image:latest"
docker push --all-tags "$image"

image_with_sha="$(docker inspect --format='{{index .RepoDigests 0}}' $image:latest)"

helm upgrade \
  --reuse-values \
  --set server.tag="$image_with_sha" \
  "$HELM_RELEASE" "$CHART_PATH"
