#!/usr/bin/env bash

# shellcheck disable=SC1090
source "$(dirname "$0")/../../.env"

kubectl port-forward postgres-0 5433:5432 > /dev/null &
# shellcheck disable=SC2064
trap 'pkill -P $$' INT SIGINT SIGTERM EXIT
until pg_isready -d "$PROD_DB_URL" > /dev/null;
  do sleep 0.1;
done
psql "$@" "$PROD_DB_URL"
