#!/usr/bin/env bash

set -euo pipefail

item=$(bw get item "$BITWARDEN_ITEM_ID")

get_field_value() {
	field_name=$1
	echo "$item" | jq -r --arg field_name "$field_name" '.fields[] | select(.name==$field_name) | .value'
}

get_field_names() {
	echo "$item" | jq -r '.fields[] | .name'
}

bw sync

k8s_secret=(
	"apiVersion: v1"
	"kind: Secret"
	"metadata:"
	"  name: fillaripolleri"
	"type: Opaque"
	"data:"
)

for field_name in $(get_field_names); do
	field_value=$(get_field_value "$field_name")
	field_value_base64=$(echo -n "$field_value" | base64)
	k8s_secret+=("  $field_name: $field_value_base64")
done

k8s_secret_string=$(
	IFS=$'\n'
	echo "${k8s_secret[*]}"
)

echo "$k8s_secret_string" | kubectl apply -f -
