#!/usr/bin/env bash

set -euo pipefail

# shellcheck disable=SC1091
source "$(dirname "$0")/../../.env"

kubectl port-forward postgres-0 5433:5432 > /dev/null &
# shellcheck disable=SC2064
trap 'pkill -P $$' INT SIGINT SIGTERM EXIT
until pg_isready -d "$PROD_DB_URL" > /dev/null;
  do sleep 0.1;
done

pg_args=('--verbose' '--clean' '--no-acl' '--no-owner')

pg_dump "${pg_args[@]}" -d "$PROD_DB_URL" -Fc \
  | pg_restore "${pg_args[@]}" -d "$DATABASE_URL"
