#!/usr/bin/env bash

set -euo pipefail

remote_ip=95.216.172.63
local_port=54322
service='postgres'
database='fillaritori'

# shellcheck disable=SC2029
postgres_ip=$(ssh $remote_ip "dokku postgres:info $service --internal-ip")
# shellcheck disable=SC2029
dsn=$(ssh $remote_ip "dokku postgres:info $service --dsn")
# shellcheck disable=SC2001
tunneled_url=$(echo "$dsn" | sed "s/dokku-postgres-$service:5432/localhost:$local_port/" | sed "s/\/postgres$/\/$database/")

ssh -M -S sock -fnNT -L "$local_port:$postgres_ip:5432" $remote_ip
ssh -S sock -O check $remote_ip 2> /dev/null
pg_dump --verbose --clean --no-acl --no-owner \
  -d $tunneled_url -Fc > fillaritori-$(date '+%Y%m%d').dump
ssh -S sock -O exit $remote_ip 2> /dev/null
