#!/usr/bin/env bash

set -euox pipefail

kubectl port-forward postgres-0 5433:5432 >/dev/null &

trap 'pkill -P $$' INT SIGINT SIGTERM EXIT
until pg_isready -d "$PROD_DB_URL" >/dev/null; do
	sleep 0.1
done

dump_file="$(date +%Y%m%dT%H%M%S).dump"
pg_dump --clean --no-acl --no-owner -d "$PROD_DB_URL" -Fc >"$dump_file"
