#!/usr/bin/env bash

set -euo pipefail

remote_ip=hzc-hel2
local_port=54322
service='fillaritori'
database='fillaritori'

# shellcheck disable=SC2029
postgres_ip=$(ssh $remote_ip "dokku postgres:info $service --internal-ip")
# shellcheck disable=SC2029
dsn=$(ssh $remote_ip "dokku postgres:info $service --dsn")
# shellcheck disable=SC2001
tunneled_url=$(echo "$dsn" | sed "s/dokku-postgres-$service:5432/localhost:$local_port/" | sed "s/\/postgres$/\/$database/")

echo "$tunneled_url"

ssh -M -S sock -fnNT -L "$local_port:$postgres_ip:5432" $remote_ip
ssh -S sock -O check $remote_ip 2> /dev/null
psql "$tunneled_url" "$@"
ssh -S sock -O exit $remote_ip 2> /dev/null
