#!/usr/bin/env bash

set -xeuo pipefail

image="registry.fsn.raine.dev/fillaripolleri/server"
commit="$(git rev-parse --verify HEAD)"

cd "$(git rev-parse --show-toplevel)"
docker build -t $image -f server/Dockerfile .
docker tag $image "$image:$commit"
docker tag $image "$image:latest"
docker push --all-tags "$image"

image_with_sha="$(docker inspect --format='{{index .RepoDigests 0}}' $image:latest)"

helm upgrade \
	--reuse-values \
	--set server.image="$image_with_sha" \
	"$HELM_RELEASE" "$CHART_PATH"
