#!/usr/bin/env bash

set -euox pipefail

FILLARIPOLLERI_PATH=$HOME/code/fillaripolleri
IMAGE="registry.gitlab.com/rainevi/fillaripolleri/server"
COMMIT="$(git rev-parse --verify HEAD)"

docker build -t $IMAGE .
docker tag $IMAGE $IMAGE:$COMMIT
docker tag $IMAGE $IMAGE:latest
docker push $IMAGE

SERVER_TAG=$COMMIT $FILLARIPOLLERI_PATH/helm-upgrade-release
